#include "FinalProjectDIsclaimerMessage.h"
#include <string>
#include <iostream>
using namespace std;

FinalProjectDisclaimerMessage::FinalProjectDisclaimerMessage()
{
  cout << "WARNING!!!!\nTHIS PROGRAM IS SOLELY INTENDED FOR THE USE AS A FINAL PROJECT IN ITS CURRENT STAGE AND DOES NOT CONTAIN ALL OF THE NESSACCARY MATERIAL TO BE A FULLY FUNCTIONAL PROGRAM USED FOR THE PROCESSING OF DATA AND MATERIAL. THERE MAY BE ERRORS IN WHICH THE PROGRAMMERS HAVE: A) GLOSSED OVER B) FORGOTTEN TO INCLUDE C) MISUSED FOR THE CURRENT PROGRAMMING BUILD D) NOT USED TO FULL FUNCTIONALITY.\n";
}

FinalProjectDisclaimerMessage::~FinalProjectDisclaimerMessage()
{
  cout << "WARNING!!! YOU HAVE JUST COMPLETED THE FIRST TASK OF USING THE PROGRAM, YOU MAY CONTINUE ON BUT PLEASE BE AWARE OF ANY BUGGS IN THE CODE THAT MAY NOT ALLOW THE PROGRAM TO OPERATE AT ITS FULL POTENTIAL, THIS CODE IS STILL UNDER REVISION AND MAY NOT BE A FULLY FUNCTIONAL PROGRAM FOR SOME TIME, THANK YOU FOR YOUR UNDERSTANDING OF THE SITUATUIION AND THAT WE ARE WORKING HARD TO GIVE YOU THE BEST POSSIBLE VERSION OF THE CODE IN DUE TIME.";
}
